### ISSUE TITLE
What's the temperal files *.node and *.ele in step_3?

### ISSUE THREAD

**Issue by changbozhu** [zhhoper/RI_render_DPR#3]
What's the temperal files  *.node and *.ele in step_3 ?   How could I get a new pair *.node and *.ele if possible ?
ATTACHEMENT: 
3.run bash run_node.sh 
Apply arap to further align faces in render: generate arap.obj an object of arap algorithm *.node and *.ele temperal files for applying arap

**Comment by zhhoper** [comment]
The *.node and *.ele are files containing node and face files of Delaunay triangulation. line 74-75 in file step_3/generate_node.py shows how to get *.node and *.ele. You can refer to this link for the triangulation code http://www.cs.cmu.edu/~quake/triangle.html

**Comment by changbozhu** [comment]
Yes, I have seen your specified codes and tried to run, but an error was generated. The main problem is 'sh: 1: ./useful_code/triangle_berkeley/triangle: Permission denied'.  The code ran as root on a ubuntu server.  I have compiled berkerley_triangle by make.

Details of error:
(RI_render) root@2730f2b8c967:/workspace/1-RI_render_DPR-master# ./step_3/run_node.sh 
imgHQ00000.png
Save visualization result to ./result/imgHQ00000/render/albedo_3DDFA.png
imgHQ00061.png
Save visualization result to ./result/imgHQ00061/render/albedo_3DDFA.png
imgHQ00000.png
sh: 1: ./useful_code/triangle_berkeley/triangle: Permission denied
Traceback (most recent call last):
  File "./step_3/script_generate_node.py", line 32, in <module>
    get_node(albedo_landmark, face_landmark, img.shape[1], img.shape[0], subFolder)
  File "/workspace/1-RI_render_DPR-master/step_3/generate_node.py", line 79, in get_node
    node_list =  loadNode(os.path.join(saveFolder, 'albedo_landmarks.1.node'))
  File "/workspace/1-RI_render_DPR-master/step_3/generate_node.py", line 15, in loadNode
    with open(fileName) as f:
FileNotFoundError: [Errno 2] No such file or directory: './result/imgHQ00000/render/albedo_landmarks.1.node'
DeprecationWarning: 'source deactivate' is deprecated. Use 'conda deactivate'.

**Comment by changbozhu** [comment]
Thanks. I think I have solved this problem. If possible, could you give me a copy of training codes of RI_render_DPR?

**Comment by Xin-Ding** [comment]
@changbozhu , hello, I also have the same problem when running the code of "generate_node". After unzipping the codes of "triangle_berkeley" into the document "useful_code" as the "Readme", it can't generate the files of ".node" and ".ele". Can you tell me how to make this part work? Thanks a lot for your response.

**Comment by rshiv-intel** [comment]
I ran into the same error. Two potential causes:

1. The executable `./useful_code/triangle_berkeley/triangle` does not exist. Compile the source code in `triangle_berkeley` with `$cd ./useful_code/triangle_berkeley && make all`
2. You need to set the permissions for the executable so that you can actually run it: `sudo chmod 755 triangle`
